// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Loan aggregating api
 *
 * API для управления организациями и заявками на кредит
 *
 * API version: 0.0.1
 */

package openapi

import (
	"context"
	"net/http"
)



// DefaultAPIRouter defines the required methods for binding the api requests to a responses for the DefaultAPI
// The DefaultAPIRouter implementation should parse necessary information from the http request,
// pass the data to a DefaultAPIServicer to perform the required actions, then write the service results to the http response.
type DefaultAPIRouter interface { 
	OrganizationsList(http.ResponseWriter, *http.Request)
	CreateNewOrganization(http.ResponseWriter, *http.Request)
	GetOrganizationByUUID(http.ResponseWriter, *http.Request)
	DeleteOrganizationByUUID(http.ResponseWriter, *http.Request)
	UpdateOrganizationByUUID(http.ResponseWriter, *http.Request)
	GetOrganizationByName(http.ResponseWriter, *http.Request)
	DeleteOrganizationByName(http.ResponseWriter, *http.Request)
	UpdateOrganizationByName(http.ResponseWriter, *http.Request)
	UsersList(http.ResponseWriter, *http.Request)
	CreateNewUser(http.ResponseWriter, *http.Request)
	GetUserByUUID(http.ResponseWriter, *http.Request)
	DeleteUserByUUID(http.ResponseWriter, *http.Request)
	UpdateUserByUUID(http.ResponseWriter, *http.Request)
	GetUserByEmail(http.ResponseWriter, *http.Request)
	LoanApplications(http.ResponseWriter, *http.Request)
	CreateNewLoanApplication(http.ResponseWriter, *http.Request)
	GetLoanApplicationsByIncomingOrganizationUUID(http.ResponseWriter, *http.Request)
	GetLoanApplicationsByIssueOrganizationUUID(http.ResponseWriter, *http.Request)
	GetLoanApplicationByUUID(http.ResponseWriter, *http.Request)
	DeleteLoanApplicationByUUID(http.ResponseWriter, *http.Request)
	UpdateLoanApplicationByUUID(http.ResponseWriter, *http.Request)
}


// DefaultAPIServicer defines the api actions for the DefaultAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type DefaultAPIServicer interface { 
	OrganizationsList(context.Context) (ImplResponse, error)
	CreateNewOrganization(context.Context, CreateNewOrganizationRequest) (ImplResponse, error)
	GetOrganizationByUUID(context.Context, string) (ImplResponse, error)
	DeleteOrganizationByUUID(context.Context, string) (ImplResponse, error)
	UpdateOrganizationByUUID(context.Context, string, OrganizationPatch) (ImplResponse, error)
	GetOrganizationByName(context.Context, string) (ImplResponse, error)
	DeleteOrganizationByName(context.Context, string) (ImplResponse, error)
	UpdateOrganizationByName(context.Context, string, OrganizationPatch) (ImplResponse, error)
	UsersList(context.Context) (ImplResponse, error)
	CreateNewUser(context.Context, CreateNewUserRequest) (ImplResponse, error)
	GetUserByUUID(context.Context, string) (ImplResponse, error)
	DeleteUserByUUID(context.Context, string) (ImplResponse, error)
	UpdateUserByUUID(context.Context, string, UserPatch) (ImplResponse, error)
	GetUserByEmail(context.Context, string) (ImplResponse, error)
	LoanApplications(context.Context, float32, string, string) (ImplResponse, error)
	CreateNewLoanApplication(context.Context, CreateNewLoanApplicationRequest) (ImplResponse, error)
	GetLoanApplicationsByIncomingOrganizationUUID(context.Context, string) (ImplResponse, error)
	GetLoanApplicationsByIssueOrganizationUUID(context.Context, string) (ImplResponse, error)
	GetLoanApplicationByUUID(context.Context, string) (ImplResponse, error)
	DeleteLoanApplicationByUUID(context.Context, string) (ImplResponse, error)
	UpdateLoanApplicationByUUID(context.Context, string, LoanApplicationPatch) (ImplResponse, error)
}
