// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Loan aggregating api
 *
 * API для управления организациями и заявками на кредит
 *
 * API version: 0.0.1
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// DefaultAPIService is a service that implements the logic for the DefaultAPIServicer
// This service should implement the business logic for every endpoint for the DefaultAPI API.
// Include any external packages or services that will be required by this service.
type DefaultAPIService struct {
}

// NewDefaultAPIService creates a default api service
func NewDefaultAPIService() *DefaultAPIService {
	return &DefaultAPIService{}
}

// OrganizationsList - organizations list
func (s *DefaultAPIService) OrganizationsList(ctx context.Context) (ImplResponse, error) {
	// TODO - update OrganizationsList with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []Organization{}) or use other options such as http.Ok ...
	// return Response(200, []Organization{}), nil

	// TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	// return Response(204, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("OrganizationsList method not implemented")
}

// CreateNewOrganization - Create new organization
func (s *DefaultAPIService) CreateNewOrganization(ctx context.Context, createNewOrganizationRequest CreateNewOrganizationRequest) (ImplResponse, error) {
	// TODO - update CreateNewOrganization with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(201, Organization{}) or use other options such as http.Ok ...
	// return Response(201, Organization{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("CreateNewOrganization method not implemented")
}

// GetOrganizationByUUID - Find organization by UUID
func (s *DefaultAPIService) GetOrganizationByUUID(ctx context.Context, uuid string) (ImplResponse, error) {
	// TODO - update GetOrganizationByUUID with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Organization{}) or use other options such as http.Ok ...
	// return Response(200, Organization{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetOrganizationByUUID method not implemented")
}

// DeleteOrganizationByUUID - Delete organization by UUID
func (s *DefaultAPIService) DeleteOrganizationByUUID(ctx context.Context, uuid string) (ImplResponse, error) {
	// TODO - update DeleteOrganizationByUUID with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	// return Response(200, nil),nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("DeleteOrganizationByUUID method not implemented")
}

// UpdateOrganizationByUUID - Update Organization by UUID
func (s *DefaultAPIService) UpdateOrganizationByUUID(ctx context.Context, uuid string, organizationPatch OrganizationPatch) (ImplResponse, error) {
	// TODO - update UpdateOrganizationByUUID with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Organization{}) or use other options such as http.Ok ...
	// return Response(200, Organization{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("UpdateOrganizationByUUID method not implemented")
}

// GetOrganizationByName - Find organization by name
func (s *DefaultAPIService) GetOrganizationByName(ctx context.Context, name string) (ImplResponse, error) {
	// TODO - update GetOrganizationByName with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Organization{}) or use other options such as http.Ok ...
	// return Response(200, Organization{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetOrganizationByName method not implemented")
}

// DeleteOrganizationByName - Delete organization by name
func (s *DefaultAPIService) DeleteOrganizationByName(ctx context.Context, name string) (ImplResponse, error) {
	// TODO - update DeleteOrganizationByName with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	// return Response(200, nil),nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("DeleteOrganizationByName method not implemented")
}

// UpdateOrganizationByName - Update organization by name
func (s *DefaultAPIService) UpdateOrganizationByName(ctx context.Context, name string, organizationPatch OrganizationPatch) (ImplResponse, error) {
	// TODO - update UpdateOrganizationByName with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Organization{}) or use other options such as http.Ok ...
	// return Response(200, Organization{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("UpdateOrganizationByName method not implemented")
}

// UsersList - users list
func (s *DefaultAPIService) UsersList(ctx context.Context) (ImplResponse, error) {
	// TODO - update UsersList with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []User{}) or use other options such as http.Ok ...
	// return Response(200, []User{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("UsersList method not implemented")
}

// CreateNewUser - Create new user
func (s *DefaultAPIService) CreateNewUser(ctx context.Context, createNewUserRequest CreateNewUserRequest) (ImplResponse, error) {
	// TODO - update CreateNewUser with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(201, User{}) or use other options such as http.Ok ...
	// return Response(201, User{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("CreateNewUser method not implemented")
}

// GetUserByUUID - Find user by UUID
func (s *DefaultAPIService) GetUserByUUID(ctx context.Context, uuid string) (ImplResponse, error) {
	// TODO - update GetUserByUUID with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, User{}) or use other options such as http.Ok ...
	// return Response(200, User{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetUserByUUID method not implemented")
}

// DeleteUserByUUID - Delete user by UUID
func (s *DefaultAPIService) DeleteUserByUUID(ctx context.Context, uuid string) (ImplResponse, error) {
	// TODO - update DeleteUserByUUID with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	// return Response(200, nil),nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("DeleteUserByUUID method not implemented")
}

// UpdateUserByUUID - Update User by UUID
func (s *DefaultAPIService) UpdateUserByUUID(ctx context.Context, uuid string, userPatch UserPatch) (ImplResponse, error) {
	// TODO - update UpdateUserByUUID with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, User{}) or use other options such as http.Ok ...
	// return Response(200, User{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("UpdateUserByUUID method not implemented")
}

// GetUserByEmail - Find user by E-mail
func (s *DefaultAPIService) GetUserByEmail(ctx context.Context, email string) (ImplResponse, error) {
	// TODO - update GetUserByEmail with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, User{}) or use other options such as http.Ok ...
	// return Response(200, User{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetUserByEmail method not implemented")
}

// LoanApplications - Loan applications list
func (s *DefaultAPIService) LoanApplications(ctx context.Context, value float32, incomingOrganizationUuid string, issueOrganizationUuid string) (ImplResponse, error) {
	// TODO - update LoanApplications with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []LoanApplication{}) or use other options such as http.Ok ...
	// return Response(200, []LoanApplication{}), nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("LoanApplications method not implemented")
}

// CreateNewLoanApplication - Create new loan application
func (s *DefaultAPIService) CreateNewLoanApplication(ctx context.Context, createNewLoanApplicationRequest CreateNewLoanApplicationRequest) (ImplResponse, error) {
	// TODO - update CreateNewLoanApplication with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(201, LoanApplication{}) or use other options such as http.Ok ...
	// return Response(201, LoanApplication{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("CreateNewLoanApplication method not implemented")
}

// GetLoanApplicationsByIncomingOrganizationUUID - Find loan applications by incoming organization UUID
func (s *DefaultAPIService) GetLoanApplicationsByIncomingOrganizationUUID(ctx context.Context, incomingOrganizationUuid string) (ImplResponse, error) {
	// TODO - update GetLoanApplicationsByIncomingOrganizationUUID with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []LoanApplication{}) or use other options such as http.Ok ...
	// return Response(200, []LoanApplication{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetLoanApplicationsByIncomingOrganizationUUID method not implemented")
}

// GetLoanApplicationsByIssueOrganizationUUID - Find loan applications by issue organization UUID
func (s *DefaultAPIService) GetLoanApplicationsByIssueOrganizationUUID(ctx context.Context, issueOrganizationUuid string) (ImplResponse, error) {
	// TODO - update GetLoanApplicationsByIssueOrganizationUUID with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []LoanApplication{}) or use other options such as http.Ok ...
	// return Response(200, []LoanApplication{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetLoanApplicationsByIssueOrganizationUUID method not implemented")
}

// GetLoanApplicationByUUID - Find loan application by UUID
func (s *DefaultAPIService) GetLoanApplicationByUUID(ctx context.Context, uuid string) (ImplResponse, error) {
	// TODO - update GetLoanApplicationByUUID with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, LoanApplication{}) or use other options such as http.Ok ...
	// return Response(200, LoanApplication{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetLoanApplicationByUUID method not implemented")
}

// DeleteLoanApplicationByUUID - Delete loan application by UUID
func (s *DefaultAPIService) DeleteLoanApplicationByUUID(ctx context.Context, uuid string) (ImplResponse, error) {
	// TODO - update DeleteLoanApplicationByUUID with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	// return Response(200, nil),nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("DeleteLoanApplicationByUUID method not implemented")
}

// UpdateLoanApplicationByUUID - Update loan application by UUID
func (s *DefaultAPIService) UpdateLoanApplicationByUUID(ctx context.Context, uuid string, loanApplicationPatch LoanApplicationPatch) (ImplResponse, error) {
	// TODO - update UpdateLoanApplicationByUUID with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, LoanApplication{}) or use other options such as http.Ok ...
	// return Response(200, LoanApplication{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("UpdateLoanApplicationByUUID method not implemented")
}
