// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Loan aggregating api
 *
 * API для управления организациями и заявками на кредит
 *
 * API version: 0.0.1
 */

package openapi




type CreateNewLoanApplicationRequest struct {

	Value float32 `json:"value"`

	IncomingOrganizationUuid string `json:"incoming_organization_uuid"`

	IssueOrganizationUuid string `json:"issue_organization_uuid"`
}

// AssertCreateNewLoanApplicationRequestRequired checks if the required fields are not zero-ed
func AssertCreateNewLoanApplicationRequestRequired(obj CreateNewLoanApplicationRequest) error {
	elements := map[string]interface{}{
		"value": obj.Value,
		"incoming_organization_uuid": obj.IncomingOrganizationUuid,
		"issue_organization_uuid": obj.IssueOrganizationUuid,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertCreateNewLoanApplicationRequestConstraints checks if the values respects the defined constraints
func AssertCreateNewLoanApplicationRequestConstraints(obj CreateNewLoanApplicationRequest) error {
	return nil
}
