// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Loan aggregating api
 *
 * API для управления организациями и заявками на кредит
 *
 * API version: 0.0.1
 */

package openapi




type CreateNewOrganizationRequest struct {

	Name string `json:"name"`

	Email string `json:"email"`
}

// AssertCreateNewOrganizationRequestRequired checks if the required fields are not zero-ed
func AssertCreateNewOrganizationRequestRequired(obj CreateNewOrganizationRequest) error {
	elements := map[string]interface{}{
		"name": obj.Name,
		"email": obj.Email,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertCreateNewOrganizationRequestConstraints checks if the values respects the defined constraints
func AssertCreateNewOrganizationRequestConstraints(obj CreateNewOrganizationRequest) error {
	return nil
}
