// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Loan aggregating api
 *
 * API для управления организациями и заявками на кредит
 *
 * API version: 0.0.1
 */

package openapi




type CreateNewUserRequest struct {

	Email string `json:"email"`

	Name string `json:"name"`
}

// AssertCreateNewUserRequestRequired checks if the required fields are not zero-ed
func AssertCreateNewUserRequestRequired(obj CreateNewUserRequest) error {
	elements := map[string]interface{}{
		"email": obj.Email,
		"name": obj.Name,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertCreateNewUserRequestConstraints checks if the values respects the defined constraints
func AssertCreateNewUserRequestConstraints(obj CreateNewUserRequest) error {
	return nil
}
