// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Loan aggregating api
 *
 * API для управления организациями и заявками на кредит
 *
 * API version: 0.0.1
 */

package openapi




type Organization struct {

	Uuid string `json:"uuid"`

	Name string `json:"name"`

	Email string `json:"email"`
}

// AssertOrganizationRequired checks if the required fields are not zero-ed
func AssertOrganizationRequired(obj Organization) error {
	elements := map[string]interface{}{
		"uuid": obj.Uuid,
		"name": obj.Name,
		"email": obj.Email,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertOrganizationConstraints checks if the values respects the defined constraints
func AssertOrganizationConstraints(obj Organization) error {
	return nil
}
