// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Loan aggregating api
 *
 * API для управления организациями и заявками на кредит
 *
 * API version: 0.0.1
 */

package openapi




type OrganizationPatch struct {

	Name string `json:"name,omitempty"`

	Email string `json:"email,omitempty"`
}

// AssertOrganizationPatchRequired checks if the required fields are not zero-ed
func AssertOrganizationPatchRequired(obj OrganizationPatch) error {
	return nil
}

// AssertOrganizationPatchConstraints checks if the values respects the defined constraints
func AssertOrganizationPatchConstraints(obj OrganizationPatch) error {
	return nil
}
