// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Loan aggregating api
 *
 * API для управления организациями и заявками на кредит
 *
 * API version: 0.0.1
 */

package openapi




type LoanApplicationPatch struct {

	Value float32 `json:"value,omitempty"`

	IncomingOrganizationUuid string `json:"incoming_organization_uuid,omitempty"`

	IssueOrganizationUuid string `json:"issue_organization_uuid,omitempty"`
}

// AssertLoanApplicationPatchRequired checks if the required fields are not zero-ed
func AssertLoanApplicationPatchRequired(obj LoanApplicationPatch) error {
	return nil
}

// AssertLoanApplicationPatchConstraints checks if the values respects the defined constraints
func AssertLoanApplicationPatchConstraints(obj LoanApplicationPatch) error {
	return nil
}
