// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Loan aggregating api
 *
 * API для управления организациями и заявками на кредит
 *
 * API version: 0.0.1
 */

package openapi




type UserPatch struct {

	Name string `json:"name,omitempty"`

	Email string `json:"email,omitempty"`
}

// AssertUserPatchRequired checks if the required fields are not zero-ed
func AssertUserPatchRequired(obj UserPatch) error {
	return nil
}

// AssertUserPatchConstraints checks if the values respects the defined constraints
func AssertUserPatchConstraints(obj UserPatch) error {
	return nil
}
