// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Loan aggregating api
 *
 * API для управления организациями и заявками на кредит
 *
 * API version: 0.0.1
 */

package openapi




type LoanApplication struct {

	Uuid string `json:"uuid"`

	Value float32 `json:"value,omitempty"`

	// Incoming organization UUID
	IncomingOrganizationUuid string `json:"incoming_organization_uuid"`

	// Issue organization UUID
	IssueOrganizationUuid string `json:"issue_organization_uuid"`
}

// AssertLoanApplicationRequired checks if the required fields are not zero-ed
func AssertLoanApplicationRequired(obj LoanApplication) error {
	elements := map[string]interface{}{
		"uuid": obj.Uuid,
		"incoming_organization_uuid": obj.IncomingOrganizationUuid,
		"issue_organization_uuid": obj.IssueOrganizationUuid,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertLoanApplicationConstraints checks if the values respects the defined constraints
func AssertLoanApplicationConstraints(obj LoanApplication) error {
	return nil
}
